server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /api/auth {
        proxy_pass http://auth-service-network:5001;
    }

    location /api/admin {
        proxy_pass http://admin-service-internal:5003;
    }

    location /api/patients {
        proxy_pass http://patient-service-internal:5002;
    }

    location /api/doctors {
        proxy_pass http://doctor-service-internal:5004;
    }

    location /api/appointments {
        proxy_pass http://appointment-service-internal:5005;
    }

    location /api/payments {
        proxy_pass http://payment-service-internal:5007;
    }

    location /api/reports {
        proxy_pass http://mediaclreport-service-internal:5006;
    }

    location /api/telemedicine {
        proxy_pass http://telemedicine-service-internal:5008;
    }

    location /api/notifications {
        proxy_pass http://notification-service-internal:5009;
    }

    location /api/prescriptions {
        proxy_pass http://doctor-service-internal:5004;
    }

    location /api/availability {
        proxy_pass http://doctor-service-internal:5004;
    }

    location /uploads/payment-slips {
        proxy_pass http://payment-service-internal:5007;
    }

    location /uploads {
        proxy_pass http://mediaclreport-service-internal:5006;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}