services:

#====================================================
#                PATIENT SERVICE
#====================================================
  patient-service:
    build:
      context: ./backend/services/patient-service
    container_name: medigo-patient-service
    ports:
      - "5002:5002"
    env_file:
      - ./backend/services/patient-service/.env

#====================================================
#                AUTH SERVICE
#====================================================
  auth-service:
    build:
      context: ./backend/services/auth-service
    container_name: medigo-auth-service
    ports:
      - "5001:5001" 
    env_file:
      - ./backend/services/auth-service/.env


#====================================================
#                ADMIN SERVICE
#====================================================
  admin-service:
    build:
      context: ./backend/services/admin-service
    container_name: medigo-admin-service
    ports:
      - "5003:5003" 
    env_file:
      - ./backend/services/admin-service/.env

#====================================================
#               PAYMENT SERVICE
#====================================================
  payment-service:
    build:
      context: ./backend/services/payment-service
    container_name: medigo-payment-service
    ports:
      - "5007:5007"
    env_file:
      - ./backend/services/payment-service/.env
    volumes:
      - ./backend/services/payment-service/uploads:/app/uploads

#====================================================
#            TELEMEDICINE SERVICE
#====================================================
  telemedicine-service:
    build:
      context: ./backend/services/telemedicine-service
    container_name: medigo-telemedicine-service
    ports:
      - "5008:5008"
    env_file:
      - ./backend/services/telemedicine-service/.env
