apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-deployment
spec:
  replicas: 2 # Runs two copies of your service for high availability
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: patient-service
        image: medigo-patient-service:latest
        imagePullPolicy: Never # Tells K8s to use your local Docker image
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        - name: MONGO_URI
          value: "mongodb+srv://medigoAdmin:mediGo%40SE127@medigo-cluster.ega902t.mongodb.net/patient_db?retryWrites=true&w=majority"