apiVersion: v1
kind: Service
metadata:
  name: admin-service-network
spec:
  type: NodePort
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      nodePort: 30003 # Hit http://localhost:30003 in Postman