apiVersion: v1
kind: Service
metadata:
  name: mediaclreport-service-network
spec:
  type: NodePort
  selector:
    app: mediaclreport-service
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
      nodePort: 30006 # Hit http://localhost:30006 for Medical Report Service API
