apiVersion: v1
kind: Service
metadata:
  name: notification-service-network
spec:
  type: NodePort
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 5009
      targetPort: 5009
      nodePort: 30009 # Hit http://localhost:30009 for this service
