apiVersion: v1
kind: Service
metadata:
  name: patient-service-network
spec:
  type: NodePort # Exposes the service so you can access it from your local machine
  selector:
    app: patient-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002 # You will hit http://localhost:30002 in Postman to reach K8s