apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: patient-service
        image: medigo-patient-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        env:
        # --- Core Settings ---
        - name: PORT
          value: "5002"
        - name: MONGO_URI
          value: "mongodb+srv://medigoAdmin:mediGo%40SE127@medigo-cluster.ega902t.mongodb.net/patient_db?retryWrites=true&w=majority"
        
        # --- Secrets & Keys ---
        - name: JWT_SECRET
          value: "medigo_super_secret_key"
        - name: SERVICE_SECRET
          value: "medigo_super_secret_key"
          
        # --- K8s Internal Networking ---
        - name: AUTH_SERVICE_URL
          value: "http://auth-service-network:5001"