apiVersion: v1
kind: ConfigMap
metadata:
  name: telemedicine-service-config
data:
  PORT: "5008"
  JITSI_BASE_URL: "https://meet.jit.si"
  APPOINTMENT_SERVICE_URL: "http://appointment-service-network:5005"
