apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  PORT: "5007"
  JWT_EXPIRES_IN: "7d"
  STRIPE_SUCCESS_URL: "http://localhost:5007/api/payments/success"
  STRIPE_CANCEL_URL: "http://localhost:5007/api/payments/cancel"
  APPOINTMENT_SERVICE_URL: "http://localhost:5005"
  NOTIFICATION_SERVICE_URL: "http://localhost:5009"
