apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
type: Opaque
stringData:
  MONGO_URI: "REPLACE_WITH_PAYMENT_MONGO_URI"
  STRIPE_SECRET_KEY: "REPLACE_WITH_STRIPE_SECRET_KEY"
  JWT_SECRET: "REPLACE_WITH_JWT_SECRET"
  SERVICE_SECRET: "REPLACE_WITH_SHARED_SERVICE_SECRET"
